import 'package:flutter/material.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedGroup992Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedHelloRushiWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2941Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2939Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedStatusbarWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedProgramsWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedXbuttonWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedHelpcircleWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedWhatdoyouwannalearntodayWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedGethelpWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2916Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2942Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2938Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedLearnWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedOutlineInterfaceMenuWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedSolidFilesBookmarkWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedOutlineStatusNotificationWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedDDTrackerWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2937Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedSolidStatusBookopenWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedLockWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedTrelloWidget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedGroup993Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedForum_black_24dp1Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedGroup994Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedGroup973Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2940Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedRectangle2946Widget.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget/generated/GeneratedXbuttonWidget1.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1458.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1458.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          // overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 24.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 276.0,
                              child: GeneratedRectangle2946Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 24.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 56.0,
                              child: GeneratedRectangle2916Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 24.0,
                              child: GeneratedStatusbarWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 28.0,
                              child: GeneratedHelloRushiWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 116.0,
                              right: null,
                              bottom: null,
                              width: 186.0,
                              height: 18.0,
                              child: GeneratedWhatdoyouwannalearntodayWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedOutlineInterfaceMenuWidget(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedOutlineStatusNotificationWidget(),
                            ),
                            Positioned(
                              left: 442.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 26.0,
                              child: GeneratedXbuttonWidget(),
                            ),
                            Positioned(
                              left: 442.0,
                              top: 962.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 26.0,
                              child: GeneratedXbuttonWidget1(),
                            ),
                            Positioned(
                              left: 440.0,
                              top: 1345.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 8.0,
                              child: GeneratedRectangle2937Widget(),
                            ),
                            Positioned(
                              left: 440.0,
                              top: 1345.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 8.0,
                              child: GeneratedRectangle2938Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 500.0,
                              height: 330.0,
                              child: GeneratedGroup994Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 1048.0,
                              right: null,
                              bottom: null,
                              width: 500.0,
                              height: 330.0,
                              child: GeneratedGroup993Widget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 500.0,
                              height: 330.0,
                              child: GeneratedGroup992Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 48.0,
                              child: GeneratedRectangle2939Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 48.0,
                              child: GeneratedRectangle2940Widget(),
                            ),
                            Positioned(
                              left: 184.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 48.0,
                              child: GeneratedRectangle2941Widget(),
                            ),
                            Positioned(
                              left: 184.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 48.0,
                              child: GeneratedRectangle2942Widget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 25.0,
                              child: GeneratedProgramsWidget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 25.0,
                              child: GeneratedLearnWidget(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 22.0,
                              child: GeneratedGethelpWidget(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 22.0,
                              child: GeneratedDDTrackerWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedSolidStatusBookopenWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedSolidFilesBookmarkWidget(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedHelpcircleWidget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 233.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child: GeneratedTrelloWidget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 0.0,
                              width: 360.0,
                              height: 56.0,
                              child: GeneratedGroup973Widget(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedForum_black_24dp1Widget(),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 1346.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedLockWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
