import 'package:flutter/material.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedXbuttonWidget3.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/Generated13FebSundayWidget3.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2942Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2946Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedSolidFilesBookmarkWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedGroup973Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/Generated13FebSundayWidget2.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedSolidStatusBookopenWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedLearnWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedForum_black_24dp1Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedGethelpWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedOutlineStatusNotificationWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedTrelloWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedOutlineInterfaceMenuWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedProgramsWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedHelloRushiWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedStatusbarWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2940Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedGroup992Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2916Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2941Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedRectangle2939Widget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedDDTrackerWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedHelpcircleWidget1.dart';
import 'package:flutterapp/design_flutterapp/generatedhomewidget5/generated/GeneratedWhatdoyouwannalearntodayWidget1.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          // overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 640.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  // overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 24.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 276.0,
                      child: GeneratedRectangle2946Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 88.0,
                      right: null,
                      bottom: null,
                      width: 117.0,
                      height: 28.0,
                      child: GeneratedHelloRushiWidget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 116.0,
                      right: null,
                      bottom: null,
                      width: 186.0,
                      height: 18.0,
                      child: GeneratedWhatdoyouwannalearntodayWidget1(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 617.0,
                      right: null,
                      bottom: null,
                      width: 146.0,
                      height: 18.0,
                      child: Generated13FebSundayWidget2(),
                    ),
                    Positioned(
                      left: 286.0,
                      top: 617.0,
                      right: null,
                      bottom: null,
                      width: 146.0,
                      height: 18.0,
                      child: Generated13FebSundayWidget3(),
                    ),
                    Positioned(
                      left: 184.0,
                      top: 612.0,
                      right: null,
                      bottom: null,
                      width: 62.0,
                      height: 26.0,
                      child: GeneratedXbuttonWidget3(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 164.0,
                      right: null,
                      bottom: null,
                      width: 160.0,
                      height: 48.0,
                      child: GeneratedRectangle2939Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 220.0,
                      right: null,
                      bottom: null,
                      width: 160.0,
                      height: 48.0,
                      child: GeneratedRectangle2940Widget1(),
                    ),
                    Positioned(
                      left: 184.0,
                      top: 164.0,
                      right: null,
                      bottom: null,
                      width: 160.0,
                      height: 48.0,
                      child: GeneratedRectangle2941Widget1(),
                    ),
                    Positioned(
                      left: 184.0,
                      top: 220.0,
                      right: null,
                      bottom: null,
                      width: 160.0,
                      height: 48.0,
                      child: GeneratedRectangle2942Widget1(),
                    ),
                    Positioned(
                      left: 72.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 25.0,
                      child: GeneratedProgramsWidget1(),
                    ),
                    Positioned(
                      left: 72.0,
                      top: 234.0,
                      right: null,
                      bottom: null,
                      width: 44.0,
                      height: 25.0,
                      child: GeneratedLearnWidget1(),
                    ),
                    Positioned(
                      left: 240.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 59.0,
                      height: 22.0,
                      child: GeneratedGethelpWidget1(),
                    ),
                    Positioned(
                      left: 240.0,
                      top: 234.0,
                      right: null,
                      bottom: null,
                      width: 77.0,
                      height: 22.0,
                      child: GeneratedDDTrackerWidget1(),
                    ),
                    Positioned(
                      left: 36.0,
                      top: 232.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedSolidStatusBookopenWidget1(),
                    ),
                    Positioned(
                      left: 36.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedSolidFilesBookmarkWidget1(),
                    ),
                    Positioned(
                      left: 208.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 20.0,
                      child: GeneratedHelpcircleWidget1(),
                    ),
                    Positioned(
                      left: 207.0,
                      top: 233.0,
                      right: null,
                      bottom: null,
                      width: 22.0,
                      height: 22.0,
                      child: GeneratedTrelloWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 24.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 56.0,
                      child: GeneratedRectangle2916Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 24.0,
                      child: GeneratedStatusbarWidget1(),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 40.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedOutlineInterfaceMenuWidget1(),
                    ),
                    Positioned(
                      left: 322.0,
                      top: 40.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedOutlineStatusNotificationWidget1(),
                    ),
                    Positioned(
                      left: 282.0,
                      top: 40.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedForum_black_24dp1Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 324.0,
                      right: null,
                      bottom: null,
                      width: 500.0,
                      height: 330.0,
                      child: GeneratedGroup992Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 0.0,
              width: 360.0,
              height: 56.0,
              child: GeneratedGroup973Widget1(),
            )
          ]),
    ));
  }
}
